distributor:
    routes:
        70c97d8d-a729-4a23-bb40-bc20e7e6e5c1:
            uuid: 70c97d8d-a729-4a23-bb40-bc20e7e6e5c1
            weight: 10000
            value:
                type: csv
                pass: ''
                config:
                    csv:
                        enabled: true
                        async: false
                        disableStorage: inherit
                        enableDataProviders:
                            type: all
                            config:
                                all: {  }
                        gate:
                            type: 'true'
                            config:
                                'true': {  }
                        data:
                            fieldMap:
                                fields: {  }
                            passthroughFields:
                                enabled: true
                            ignoreEmptyFields:
                                enabled: true
                            excludeFields:
                                fields: {  }
                            prefix:
                                prefix: ''
                                action: add
                        # TODO: What is the correct event to listen to create path from identifier before sending to the distributor-csv?
                        fileIdentifier: '/var/www/html/form-submits.csv'
                        delimiter: ';'
                        enclosure: '"'

metaData:
    name: CSV Route
    version:
        core: 1.0.0
        distributor-core: 1.0.0
        distributor-csv: 1.0.0
    includes: {  }
