valueMaps: []
identifier:
  collectors:
    pardot:
      enabled: false
distributor:
  async: false
  disableStorage: true
  routes:
    csv:
      enabled: true
      fileIdentifier: 1:/trallalala/form-submits-override.csv
      delimiter: ';'
      enclosure: '"'
      # TODO: what other settings does this route have?
      async: inherit
      disableStorage: inherit
      enableDataProviders: '*'
      gate:
        type: 'true'
        config:
          'true': []
      data:
        passthroughFields:
          enabled: true
          overwrite: false
