services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DigitalMarketingFramework\Typo3\Distributor\Csv\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    DigitalMarketingFramework\Typo3\Distributor\Csv\Registry\EventListener\DistributorRegistryUpdateEventListener:
        tags:
            - name: event.listener
              event: DigitalMarketingFramework\Typo3\Distributor\Core\Registry\Event\DistributorRegistryUpdateEvent

    DigitalMarketingFramework\Typo3\Distributor\Csv\Registry\EventListener\CoreRegistryUpdateEventListener:
        tags:
            - name: event.listener
              event: DigitalMarketingFramework\Typo3\Core\Core\Registry\Event\CoreRegistryUpdateEvent

    # static configuration document update
    DigitalMarketingFramework\Typo3\Distributor\Csv\ConfigurationDocument\Storage\EventListener\StaticConfigurationDocumentEventListener:
        tags:
            - name: event.listener
              event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentIdentifierCollectionEvent
            - name: event.listener
              event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentLoadEvent
